"""
pipeline.py — GEPA optimize_anything pipeline for kollector-scum.

Evolves the skill file (SKILL.md) via agent rollouts + LLM reflection.
"""

from __future__ import annotations

import json
import re
import time
from pathlib import Path
from typing import Any

import typer
import yaml
from openai import OpenAI  # noqa: F401
from _llm_client import make_client

import evaluator as evaluator_module
from evaluator import TaskResult, evaluate_skill


app = typer.Typer(add_completion=False, pretty_exceptions_enable=False)

REFLECTION_PROMPT = """
You are improving an AI agent skill file for the kollector-scum repository.

The current skill achieved a score of {score:.2%} on {n_tasks} coding tasks.

Failed tasks:
{failed_summaries}

Based on these failures, generate an improved version of the skill that:
1. Adds more specific guidance for the failure patterns observed
2. Makes multi-tenancy rules even more explicit if any failures involved cross-tenant data
3. Adds concrete examples where abstract rules failed
4. Does NOT remove existing correct guidance

Return the COMPLETE improved skill text (not just the changes).
""".strip()

COPILOT_HEADER = "<!-- This file is auto-generated by gskill-kollector. Do not edit manually. -->\n"

# GitHub Models API has an 8000 token limit. Reserve ~2000 tokens for the prompt
# and failed summaries; limit the skill body to ~4000 tokens (~16000 chars at 4 chars/token).
_MAX_SKILL_CHARS = 16_000


def _extract_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    stripped = text.lstrip()
    if not stripped.startswith("---\n"):
        return {}, text.strip() + "\n"

    fm_end = stripped.find("\n---\n", 4)
    if fm_end == -1:
        return {}, text.strip() + "\n"

    fm_text = stripped[4:fm_end]
    body = stripped[fm_end + len("\n---\n") :].lstrip("\n")
    try:
        data = yaml.safe_load(fm_text) or {}
    except Exception:  # noqa: BLE001
        data = {}
    return data, body.strip() + "\n"


def _bump_version(version: str) -> str:
    match = re.match(r"^(\d+)\.(\d+)\.(\d+)$", version.strip())
    if not match:
        return "0.1.0"
    major, minor, patch = (int(group) for group in match.groups())
    return f"{major}.{minor}.{patch + 1}"


def load_skill(skill_path: Path) -> str:
    """Read SKILL.md and return body without YAML frontmatter."""
    text = skill_path.read_text(encoding="utf-8")
    _, body = _extract_frontmatter(text)
    return body


def save_skill(skill_text: str, skill_path: Path, copilot_path: Path) -> None:
    """
    Write updated skill body to SKILL.md with bumped frontmatter version.
    If copilot_path points to another SKILL.md, write frontmatter there as well.
    Otherwise write body-only Copilot instructions file with standard header comment.
    """
    existing_text = skill_path.read_text(encoding="utf-8") if skill_path.exists() else ""
    frontmatter, _ = _extract_frontmatter(existing_text)

    if not frontmatter:
        frontmatter = {
            "name": "kollector-scum",
            "version": "0.1.0",
            "description": "AI agent skill for contributing to the kollector-scum music catalog SaaS",
            "tags": ["dotnet", "csharp", "nextjs", "typescript", "postgresql", "multitenancy"],
        }
    else:
        frontmatter["version"] = _bump_version(str(frontmatter.get("version", "0.1.0")))

    frontmatter_yaml = yaml.safe_dump(frontmatter, sort_keys=False).strip()
    normalized_body = skill_text.strip() + "\n"
    rendered_skill = f"---\n{frontmatter_yaml}\n---\n\n{normalized_body}"

    # Ensure parent directories exist for both targets
    skill_path.parent.mkdir(parents=True, exist_ok=True)
    copilot_path.parent.mkdir(parents=True, exist_ok=True)

    # Write canonical SKILL.md for the primary skill_path
    skill_path.write_text(rendered_skill, encoding="utf-8")

    # If the copilot_path is itself a SKILL.md, write a SKILL.md there too (add copilot-skill tag)
    if copilot_path.name.lower() == "skill.md":
        try:
            copilot_front = dict(frontmatter) if isinstance(frontmatter, dict) else {}
            tags = copilot_front.get("tags") or []
            if isinstance(tags, list):
                if "copilot-skill" not in tags:
                    tags = ["copilot-skill"] + tags
                copilot_front["tags"] = tags
            copilot_front_yaml = yaml.safe_dump(copilot_front, sort_keys=False).strip()
            rendered_copilot_skill = f"---\n{copilot_front_yaml}\n---\n\n{normalized_body}"
        except Exception:
            rendered_copilot_skill = rendered_skill
        copilot_path.write_text(rendered_copilot_skill, encoding="utf-8")
    else:
        # Legacy body-only copilot instructions file
        rendered_copilot = (
            f"{COPILOT_HEADER}"
            "# Kollector Scum — Copilot Coding Agent Instructions\n\n"
            f"{normalized_body}"
        )
        copilot_path.write_text(rendered_copilot, encoding="utf-8")


def _build_failed_summaries(results: list[TaskResult]) -> str:
    failures = [result for result in results if not result.passed]
    if not failures:
        return "- None"
    lines: list[str] = []
    for result in failures:
        short_patch = (result.agent_patch or "").strip().replace("\n", " ")[:240]
        lines.append(f"- {result.task_id}: {result.error or 'task failed'}")
        if short_patch:
            lines.append(f"  patch_excerpt: {short_patch}")
    return "\n".join(lines)


def _generate_candidate_skills(
    *,
    current_skill: str,
    score: float,
    results: list[TaskResult],
    model: str,
    n_candidates: int = 3,
) -> list[str]:
    client = make_client()
    failed_summaries = _build_failed_summaries(results)
    prompt = REFLECTION_PROMPT.format(
        score=score,
        n_tasks=len(results),
        failed_summaries=failed_summaries,
    )

    candidates: list[str] = []
    # Truncate skill to fit within model token limits (GitHub Models: 8000 tokens)
    skill_excerpt = current_skill[:_MAX_SKILL_CHARS]
    if len(current_skill) > _MAX_SKILL_CHARS:
        skill_excerpt += "\n\n[... skill truncated for token limit ...]"

    # Request multiple candidates in a single API call (reduce rate-limit exposure)
    for attempt in range(6):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {
                        "role": "system",
                        "content": "You improve repository-specific coding-agent skill files.",
                    },
                    {
                        "role": "user",
                        "content": (
                            f"{prompt}\n\nCurrent skill text:\n\n{skill_excerpt}\n"
                        ),
                    },
                ],
                temperature=0.6,
                n=n_candidates,
            )
            break
        except Exception as e:
            if "429" in str(e) or "RateLimitReached" in str(e):
                wait = 60 * (attempt + 1)
                print(f"[rate-limit] waiting {wait}s (attempt {attempt + 1}/6)…")
                time.sleep(wait)
            else:
                raise
    else:
        print("[warn] all retries exhausted for candidate generation, returning empty list")
        return candidates

    # Parse all returned choices
    raw_choices = getattr(response, "choices", []) or response.get("choices", []) if isinstance(response, dict) else getattr(response, "choices", [])
    for ch in raw_choices:
        try:
            # support OpenAI-like objects and dicts
            content = getattr(ch.message, "content", None) if not isinstance(ch, dict) else ch.get("message", {}).get("content") or ch.get("text")
        except Exception:
            content = None
        if not content and isinstance(ch, dict):
            # fallback
            content = ch.get("text") or ch.get("output")
        if not content:
            try:
                content = str(ch)
            except Exception:
                continue
        candidate = content.strip()
        if candidate:
            candidates.append(candidate)

    return candidates


def fallback_evolutionary_loop(
    *,
    initial_skill: str,
    max_evals: int,
    tasks_dir: Path,
    repo_dir: Path,
    eval_script: Path,
    model: str,
    skill_path: Path,
    copilot_path: Path,
    max_workers: int,
) -> dict[str, Any]:
    """
    Simple fallback loop used when GEPA is unavailable.
    """
    history: list[dict[str, Any]] = []
    best_skill = initial_skill
    best_score = -1.0
    eval_count = 0
    round_index = 0

    while eval_count < max_evals:
        round_index += 1
        current_score, current_results = evaluate_skill(
            skill_text=best_skill,
            tasks_dir=tasks_dir,
            repo_dir=repo_dir,
            eval_script=eval_script,
            model=model,
            max_workers=max_workers,
        )
        eval_count += 1

        if current_score > best_score:
            best_score = current_score

        round_record: dict[str, Any] = {
            "round": round_index,
            "current_score": current_score,
            "best_score": best_score,
            "current_failures": [
                {"task_id": result.task_id, "error": result.error}
                for result in current_results
                if not result.passed
            ],
            "candidate_scores": [],
        }

        candidates = _generate_candidate_skills(
            current_skill=best_skill,
            score=current_score,
            results=current_results,
            model=model,
            n_candidates=3,
        )

        selected_skill = best_skill
        selected_score = current_score
        for candidate in candidates:
            if eval_count >= max_evals:
                break
            candidate_score, _ = evaluate_skill(
                skill_text=candidate,
                tasks_dir=tasks_dir,
                repo_dir=repo_dir,
                eval_script=eval_script,
                model=model,
                max_workers=max_workers,
            )
            eval_count += 1
            round_record["candidate_scores"].append(candidate_score)
            if candidate_score > selected_score:
                selected_skill = candidate
                selected_score = candidate_score

        best_skill = selected_skill
        best_score = max(best_score, selected_score)
        round_record["selected_score"] = selected_score
        round_record["eval_count"] = eval_count
        history.append(round_record)

        save_skill(best_skill, skill_path, copilot_path)
        if eval_count >= max_evals:
            break

    return {
        "mode": "fallback",
        "max_evals": max_evals,
        "eval_count": eval_count,
        "best_score": best_score,
        "history": history,
        "best_skill": best_skill,
    }


@app.command()
def main(
    max_evals: int = typer.Option(50, "--max-evals"),
    tasks_dir: Path = typer.Option(Path("tasks/"), "--tasks-dir"),
    model: str = typer.Option("gpt-4o", "--model"),
    skill_path: Path = typer.Option(Path("../.claude/skills/kollector-scum/SKILL.md"), "--skill-path"),
    copilot_path: Path = typer.Option(Path("../.github/skills/kollector-scum/SKILL.md"), "--copilot-path"),
    max_workers: int = typer.Option(4, "--max-workers"),
) -> None:
    """
    Run GEPA optimize_anything or fallback evolutionary optimization.
    """
    skill_path = skill_path.resolve()
    copilot_path = copilot_path.resolve()
    tasks_dir = tasks_dir.resolve()
    repo_dir = Path("..").resolve()
    eval_script = Path("swesmith_config/eval.sh").resolve()
    results_path = Path("pipeline_results.json").resolve()

    initial_skill = load_skill(skill_path)

    evaluator_module._config.update(
        {
            "tasks_dir": tasks_dir,
            "repo_dir": repo_dir,
            "eval_script": eval_script,
            "model": model,
            "max_workers": max_workers,
        }
    )

    try:
        from gepa import optimize_anything
    except ImportError:
        payload = fallback_evolutionary_loop(
            initial_skill=initial_skill,
            max_evals=max_evals,
            tasks_dir=tasks_dir,
            repo_dir=repo_dir,
            eval_script=eval_script,
            model=model,
            skill_path=skill_path,
            copilot_path=copilot_path,
            max_workers=max_workers,
        )
        best_skill = payload["best_skill"]
    else:
        result = optimize_anything(
            initial_prompt=initial_skill,
            evaluate_fn=evaluator_module.evaluate_skill_fn,
            max_evals=max_evals,
            population_size=5,
        )

        if isinstance(result, dict):
            best_skill = result.get("best_prompt") or result.get("prompt") or initial_skill
        else:
            best_skill = getattr(result, "best_prompt", None) or getattr(result, "prompt", None) or initial_skill

        final_score, final_results = evaluate_skill(
            skill_text=best_skill,
            tasks_dir=tasks_dir,
            repo_dir=repo_dir,
            eval_script=eval_script,
            model=model,
            max_workers=max_workers,
        )

        payload = {
            "mode": "gepa",
            "max_evals": max_evals,
            "best_score": final_score,
            "final_failures": [
                {"task_id": item.task_id, "error": item.error}
                for item in final_results
                if not item.passed
            ],
            "raw_result": result if isinstance(result, dict) else str(result),
            "best_skill": best_skill,
        }

    save_skill(best_skill, skill_path, copilot_path)
    results_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    typer.echo(f"Wrote {skill_path}")
    typer.echo(f"Wrote {copilot_path}")
    typer.echo(f"Wrote {results_path}")


if __name__ == "__main__":
    app()
