// <auto-generated />
using System;
using KollectorScum.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KollectorScum.Api.Migrations
{
    [DbContext(typeof(KollectorScumDbContext))]
    [Migration("20251211000815_AddListsFeature")]
    partial class AddListsFeature
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal BuildTargetModel required for tooling; the full model snapshot
            // is in KollectorScumDbContextModelSnapshot. This is intentionally
            // minimal to allow EF tools to discover the migration.
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");
        }
    }
}
